FROM gcr.io/dataflow-templates-base/python3-template-launcher-base:latest

WORKDIR /template

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app ./app
COPY deploy ./deploy
COPY setup.py .

ENV PYTHONPATH=/template

ENV FLEX_TEMPLATE_PYTHON_PY_FILE=app/dataflow_main.py
ENV FLEX_TEMPLATE_PYTHON_REQUIREMENTS_FILE=requirements.txt
ENV FLEX_TEMPLATE_PYTHON_SETUP_FILE=/template/setup.py